### ISSUE TITLE
Add daily (nightly) build support

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#216]
A [daily build](https://en.wikipedia.org/wiki/Daily_build) is helpful to those who want to try some new features of KubeSphere DevOps.

* A nightly build could be a candidate of a release
* A nightly build is suitable for e2e tests

Why don't just use the `latest` or `master` version?

* `latest` version is always changing. It's impossible to track down if someone meets an issue.
* `latest` image tag might lead to some cache-related problems
* no way to use KubeSphere if there is one fatal issue leak into the `master` branch

## TODO

Make sure [ks-installer](https://github.com/kubesphere/ks-installer/blob/883e1b5896020fb7aa4375cc431077d89fa64ed4/roles/download/defaults/main.yml#L154) and [kubekey](https://github.com/kubesphere/kubekey) can work well.

- [x] change the image tag name of DevOps in ks-installer
- [x] Add GitHub actions to trigger nightly build (see example in [kubesphere/kubesphere](https://github.com/kubesphere/kubesphere/blob/3ddb05b8bfd822b98bb767af0d4cdda7ad6f752c/.github/workflows/nightly-builds.yml))
- [x] create a release [v3.1.1-rc.1](https://github.com/kubesphere/ks-installer/blob/883e1b5896020fb7aa4375cc431077d89fa64ed4/roles/download/defaults/main.yml#L65)

## References

* https://github.com/kubesphere/ks-installer/blob/883e1b5896020fb7aa4375cc431077d89fa64ed4/.github/workflows/nightly-builds.yml#L26
