### ISSUE TITLE
Release 3.2 checklist

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#217]
In order to make sure don't forget anything, please get the following checklist items done before release:

Dev checklist:
- [ ] Check if there are any unstable versions in the [go.mod](https://github.com/kubesphere/ks-devops/blob/master/go.mod) file
- [ ] Upgrade test from v3.1.1 to v3.2 candidate
- [ ] others

New Features:
- [ ] Support to change Jenkins config via a ConfigMap
  * kubesphere-devops-system/jenkins-casc-config
  * change `jenkins_user.yaml` 
- [ ] Pipeline GC feature ([details](https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/795e0bb8dc27f8163557eb58c05f6c90703bf11b/charts/ks-devops/values.yaml#L17))
- [ ] Add PipelineRun which represents a build record of a Pipeline
  See https://github.com/kubesphere/ks-devops/issues/41
- [ ] Feature: support run DevOps on dockerless (contained, podman)

Ready
ks-devops branch release-3.2 https://github.com/kubesphere/ks-devops/tree/release-3.2

**Comment by JohnNiang** [comment]
- [ ] Update helm chart in ks-installer.

**Comment by JohnNiang** [comment]
- [ ] Release https://github.com/kubesphere/ks-jenkins
- [ ] Release https://github.com/kubesphere/devops-agent

**Comment by JohnNiang** [comment]
Docker images:

- kubespheredev/devops-apiserver:v3.2.0
- kubespheredev/devops-controller:v3.2.0
- kubespheredev/devops-tools:v3.2.0
- kubespheredev/ks-jenkins:3.2.0-2.249.1
- kubespheredev/builder-base:v3.2.0
- kubespheredev/builder-nodejs:v3.2.0
- kubespheredev/builder-maven:v3.2.0
- kubespheredev/builder-go:v3.2.0
- kubespheredev/builder-go:v3.2.0-1.16
- kubespheredev/java-8-centos7:v3.2.0
- kubespheredev/java-8-runtime:v3.2.0
- kubespheredev/java-11-centos7:v3.2.0
- kubespheredev/tomcat85-java11-centos7:v3.2.0
- kubespheredev/tomcat85-java8-centos7:v3.2.0
- kubespheredev/s2irun:v3.2.0
- kubespheredev/s2ioperator:v3.2.0
